//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdemyMvcPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int ID { get; set; }
        public string SocialmediaName { get; set; }
        public string Link { get; set; }
        public string İcon { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
